spring.data.mongodb.host=mongodb-docker-walmart
spring.data.mongodb.port=27017
spring.data.mongodb.database=walmart
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
server.error.include-message = always
