version: "3"
services:
  spring-walmart:
    image: mfignacio12/spring-walmart:latest
    container_name: spring-walmart
    ports:
      - 8080:8080
    links:
      - mongodb-docker-walmart
  mongodb-docker-walmart:
      image: mfignacio12/mongo:latest
      container_name: "mongodb-docker-walmart"
      ports:
        - 27017:27017